language: cpp

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt532 -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt53base qt53declarative qt53quick1 qt53quickcontrols
script:
    - source /opt/qt53/bin/qt53-env.sh
    - qmake -v
    - qmake -r
    - make
    - ls
    - ls build
    - ls lib
