language: cpp

before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt51-qmake qtbase51-dev qtdeclarative51-dev libqt5webkit51-dev
script:
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make
